version: "3.9"

services:
  backend1:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LOG_FILE_NAME=backend1
    volumes:
      - ./backend/logs:/app/logs
  backend2:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    environment:
      - LOG_FILE_NAME=backend2
    volumes:
      - ./backend/logs:/app/logs

  frontend1:
    build: ./frontend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www:ro
      - access_log_vol:/var/log/nginx/
    ports:
      - "80:8000"
    depends_on:
      - backend1
      - backend2
      - frontend1

volumes:
  access_log_vol:
