version: "3.9"

services:
  backend1:
    build: ./backend
    ports:
      - "8080:8080"
  backend2:
    build: ./backend

  frontend1:
    build: ./frontend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www:ro
      - access_log_vol:/var/log/nginx/
    ports:
      - "80:8000"
    depends_on:
      - backend1
      - backend2
      - frontend1

volumes:
  access_log_vol:
